# Generated by `mise run jinja:Containerfile`. Edit this file, not ./Containerfile.
FROM docker.io/library/node:26.8.2-trixie AS build

COPY --chown=1000:1000 ./site /site

USER 1000:1000
WORKDIR /site

RUN npm install && \
    npm run astro -- telemetry disable

ENTRYPOINT []
EXPOSE 4321
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
